import { Disco } from "@/types/Disco"

export default function getDiscos(): Disco[] {
  const discos: Disco[] = [
    {
      nombre: "El último titán",
      portada:
        "https://mp3.hhgroups.com/albumes/Predy-Delantera_El-ultimo-titan-9795.jpg",
      fechaSalida: "2009-06-08",
      colaboradores: ["Palay", "Chucky"],
      descargas: 9482,
      points: 576,
      descripcion:
        "Bienvenido a El Último Titán. La temática general de las letras es de carácter variado, cuenta con temas más nostálgicos hablando de la generación de los 80, también hay de competición como El Último Titán, alguno que abarca temas de carácter mas personal como quieren ser mayores, para los fans del hardcore he preparado AK47 y para admiradores del skate compuse predyflip 360. Debido a mi pasión por la mitología griega introduje el tema de Contra el olimpo que explica un poco el nombre de la maqueta, aparte de muchos más. Para este trabajo, he querido romper con la rutina (puesto que llevaba un año que solo sacaba colaboraciones) y he decidido meter solo un tema con Palay, aunque también cuento con otras colaboraciones vocales en estribillos y frases esporádicas en algunos temas. Para los curiosos que se pregunten qué haré después he querido meter un bonus a modo de adelanto de lo que será Proyecto Dharma (grupo formado con Chucky). www.myspace.com/lepredy He colgado material exclusivo como las letras de la maqueta, imágenes promocionales, diseños etc. Pasaros por el website para encontrar mas material gratuito:  www.predy.es Email de contacto: elpredy@hotmail.com",
      canciones: [
        {
          order: 1,
          titulo: "Dale duro",
          producedBy: "J Bravo",
          link: "https://example.com/estrellas-danzantes.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 2,
          titulo: "Xpresat",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 3,
          titulo: "El último titán",
          producedBy: "Predy",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: true,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 4,
          titulo: "Predyflip 360",
          producedBy: "Joanarman",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 5,
          titulo: "Quieren ser mayores",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 6,
          titulo: "Rapicidio",
          producedBy: "Joanarman",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 7,
          titulo: "AK47",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Palay",
          tieneVideoclip: true,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 8,
          titulo: "Generación 80",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 9,
          titulo: "Contra el olimpo",
          producedBy: "Predy",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 10,
          titulo: "Tocamela otra vez",
          producedBy: "Predy",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 11,
          titulo: "Dharmaggedon",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          featuring: "Chucky",
          urlVideoclip: "",
          duracion: "",
        },
      ],
    },

    {
      nombre: "2.0",
      portada:
        "https://mp3.hhgroups.com/albumes/Predy-Delantera_El-ultimo-titan-9795.jpg",
      fechaSalida: "2010-08-16",
      colaboradores: ["Eneko y Gareta", "Dj Erixon, Smilita, Koar, Bikos"],
      descargas: 6372,
      points: 322,
      descripcion:
        '2.0 Es el último trabajo de Predy donde notaremos un cambio en cuanto a estética y letras. Cuenta con temas más polémicos hablando de la piratería enfocándolo desde otro punto de vista, otros más temáticos bajo el género del diseño, y lo que es el single de esta maqueta "Electroman", además también incluye un remix de el tema de "El último titán". En la parte instrumental contamos con colaboraciones de Snak (RMD), Madrid Produze y Dj Wane. Los mcs colaboradores de este trabajo son: Eneko y Gareta, Smilita, Koar y Bikos. Todos los scratches corren a cuenta de Dj Erixon. Espero que disfrutéis de este trabajo. Más info:www.predy.es',

      canciones: [
        {
          order: 1,
          titulo: "Pirateria on",
          producedBy: "Snak",
          link: "https://example.com/estrellas-danzantes.mp3",
          featuring: "Dj Erixon",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 2,
          titulo: "Rabia contenida",
          producedBy: "Madrid produce",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Eneko y Gareta",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 3,
          titulo: "Electroman",
          producedBy: "Predy",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: true,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 4,
          titulo: "Dyseno flow",
          producedBy: "Predy",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Smilita",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 5,
          titulo: "Y para colmo",
          producedBy: "Snak",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 6,
          titulo: "2.0 evolution",
          producedBy: "Predy",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 7,
          titulo: "El ultimo titan (Remix)",
          producedBy: "Dj Wane",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
      ],
    },

    {
      nombre: "Dopamina",
      portada:
        "https://mp3.hhgroups.com/albumes/Predy-Delantera_El-ultimo-titan-9795.jpg",
      fechaSalida: "2012-07-12",
      colaboradores: ["Kapo", "Koar", "Smilita", "Kar"],
      descargas: 3013,
      points: 78,
      descripcion:
        "Dopamina es una maqueta que prueba hacer un tipo de rap diferente intentándolo enfocar un poco mas hacia un lado cómico y humorístico y intentando dar un rollo mas positivo al hiphop de hoy en día, cuanta con colaboraciones de Koar, Smilita, Kapo y Kar. Contacto:www.predy.es",
      canciones: [
        {
          order: 1,
          titulo: "La primera en la frente",
          producedBy: "",
          link: "https://example.com/estrellas-danzantes.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 2,
          titulo: "No me dejan",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: true,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 3,
          titulo: "Popeye el infiel",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Kapo 013",
          tieneVideoclip: true,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 4,
          titulo: "Voy a romper internet",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Smilita",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 5,
          titulo: "Danger",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Koar",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 6,
          titulo: "Hiphoputa",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 7,
          titulo: "Duchafobia",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 8,
          titulo: "Almas de barrio",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Kar",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 9,
          titulo: "Lo sé, canto mal",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 10,
          titulo: "Rap game",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 11,
          titulo: "Fapman",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 12,
          titulo: "Dos caminos",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Smilita",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 13,
          titulo: "Marketing de managers",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 14,
          titulo: "Cntr + rap + supr",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 15,
          titulo: "Salgo poco de fiesta",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
      ],
    },

    {
      nombre: "Inestable",
      portada:
        "https://mp3.hhgroups.com/albumes/Predy-Delantera_El-ultimo-titan-9795.jpg",
      fechaSalida: "2014-07-12",
      colaboradores: ["Blon", "Dakob, Dj Dolmen, Kapo 013, Dawizard"],
      descargas: 1699,
      points: 22,
      descripcion:
        "Vuelve Predy con otro trabajo experimental, mas nostálgico, mas cachondo, mas loco, en definitiva mas... Predy, un disco que pretende separarse de la corriente rapistica que se esta haciendo en la actualidad, probando diferentes géneros, como el tecno, dubstep, y enfocándolo como ya viene siendo habitual desde el punto de vista del humor.",

      canciones: [
        {
          order: 1,
          titulo: "Hello world",
          producedBy: "",
          link: "https://example.com/estrellas-danzantes.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 2,
          titulo: "Inestable",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 3,
          titulo: "Se cagan encima",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: true,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 4,
          titulo: "Acuérdate de mi cuando seas famoso",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Blon",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 5,
          titulo: "En mis tiempos",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Dakob",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 6,
          titulo: "Ponte eufórico mix",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 7,
          titulo: "La mierda sabe a chocolate",
          producedBy: "Dj Dolmen",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 8,
          titulo: "Mitades",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Kapo",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 9,
          titulo: "What? what?",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 10,
          titulo: "Espantatias",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 11,
          titulo: "Tengo un amigo que...",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Dawizard",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
        {
          order: 12,
          titulo: "Toma!",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
        },
      ],
    },
  ]

  return discos
}

const discos = getDiscos()

/* 

1.La primera en la frenteEscuchar Predy - La primera en la frenteAñadir Predy - La primera en la frente a un playlistDescargar Predy - La primera en la frenteTrack sin letra... ¿quieres mandárnosla?
02.No me dejanEscuchar Predy - No me dejanAñadir Predy - No me dejan a un playlistDescargar Predy - No me dejanTrack sin letra... ¿quieres mandárnosla?
03.Popeye el infiel (con Kapo)Escuchar Predy - Popeye el infiel (con Kapo)Añadir Predy - Popeye el infiel (con Kapo) a un playlistDescargar Predy - Popeye el infiel (con Kapo)Track sin letra... ¿quieres mandárnosla?
04.Voy a romper internet (con Smilita)Escuchar Predy - Voy a romper internet (con Smilita)Añadir Predy - Voy a romper internet (con Smilita) a un playlistDescargar Predy - Voy a romper internet (con Smilita)Track sin letra... ¿quieres mandárnosla?
05.Danger (con Koar)Escuchar Predy - Danger (con Koar)Añadir Predy - Danger (con Koar) a un playlistDescargar Predy - Danger (con Koar)Track sin letra... ¿quieres mandárnosla?
06.HiphoputaEscuchar Predy - HiphoputaAñadir Predy - Hiphoputa a un playlistDescargar Predy - HiphoputaTrack sin letra... ¿quieres mandárnosla?
07.DuchafobiaEscuchar Predy - DuchafobiaAñadir Predy - Duchafobia a un playlistDescargar Predy - DuchafobiaTrack sin letra... ¿quieres mandárnosla?
08.Almas de barrio (con Kar)Escuchar Predy - Almas de barrio (con Kar)Añadir Predy - Almas de barrio (con Kar) a un playlistDescargar Predy - Almas de barrio (con Kar)Track sin letra... ¿quieres mandárnosla?
09.Lo se canto malEscuchar Predy - Lo se canto malAñadir Predy - Lo se canto mal a un playlistDescargar Predy - Lo se canto malTrack sin letra... ¿quieres mandárnosla?
10.Rap gameEscuchar Predy - Rap gameAñadir Predy - Rap game a un playlistDescargar Predy - Rap gameTrack sin letra... ¿quieres mandárnosla?
11.FapmanEscuchar Predy - FapmanAñadir Predy - Fapman a un playlistDescargar Predy - FapmanTrack sin letra... ¿quieres mandárnosla?
12.Dos caminos (con Smilita)Escuchar Predy - Dos caminos (con Smilita)Añadir Predy - Dos caminos (con Smilita) a un playlistDescargar Predy - Dos caminos (con Smilita)Track sin letra... ¿quieres mandárnosla?
13.Marketing de managersEscuchar Predy - Marketing de managersAñadir Predy - Marketing de managers a un playlistDescargar Predy - Marketing de managersTrack sin letra... ¿quieres mandárnosla?
14.CntrrapsuprEscuchar Predy - CntrrapsuprAñadir Predy - Cntrrapsupr a un playlistDescargar Predy - CntrrapsuprTrack sin letra... ¿quieres mandárnosla?
15.Salgo poco de fiesta
 */
