import { Disco } from "@/types/Disco"

export default function getDiscos(): Disco[] {
  const discos: Disco[] = [
    {
      id: "0c0d8655-2682-43c5-8eb8-ea27ec1af7f9",
      nombre: "El último titán",
      portada:
        "https://mp3.hhgroups.com/albumes/Predy-Delantera_El-ultimo-titan-9795.jpg",
      contraportada:
        "https://mp3.hhgroups.com/albumes/Predy-Trasera_El-ultimo-titan-9795.jpg",
      fechaSalida: "2009-06-08",
      colaboradores: ["Palay", "Chucky"],
      descargas: 9482,
      points: 576,
      descripcion:
        "Bienvenido a El Último Titán. La temática general de las letras es de carácter variado, cuenta con temas más nostálgicos hablando de la generación de los 80, también hay de competición como El Último Titán, alguno que abarca temas de carácter mas personal como quieren ser mayores, para los fans del hardcore he preparado AK47 y para admiradores del skate compuse predyflip 360. Debido a mi pasión por la mitología griega introduje el tema de Contra el olimpo que explica un poco el nombre de la maqueta, aparte de muchos más. Para este trabajo, he querido romper con la rutina (puesto que llevaba un año que solo sacaba colaboraciones) y he decidido meter solo un tema con Palay, aunque también cuento con otras colaboraciones vocales en estribillos y frases esporádicas en algunos temas. Para los curiosos que se pregunten qué haré después he querido meter un bonus a modo de adelanto de lo que será Proyecto Dharma (grupo formado con Chucky). www.myspace.com/lepredy He colgado material exclusivo como las letras de la maqueta, imágenes promocionales, diseños etc. Pasaros por el website para encontrar mas material gratuito:  www.predy.es Email de contacto: elpredy@hotmail.com",
      canciones: [
        {
          order: 1,
          titulo: "Dale duro",
          producedBy: "J Bravo",
          link: "https://example.com/estrellas-danzantes.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "01. Predy - Dale duro",
          videoAudio: "",
        },
        {
          order: 2,
          titulo: "Xpresat",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "02. Predy - Xpresat",
          videoAudio: "",
        },
        {
          order: 3,
          titulo: "El último titán",
          producedBy: "Predy",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: true,
          urlVideoclip: "",
          duracion: "",
          audio: "03. Predy - El ultimo titan",
          videoAudio: "",
        },
        {
          order: 4,
          titulo: "Predyflip 360",
          producedBy: "Joanarman",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "04. Predy - Predyflip 360",
          videoAudio: "",
        },
        {
          order: 5,
          titulo: "Quieren ser mayores",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "05. Predy - Quieren ser mayores",
          videoAudio: "",
        },
        {
          order: 6,
          titulo: "Rapicidio",
          producedBy: "Joanarman",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "06. Predy - Rapicidio",
          videoAudio: "",
        },
        {
          order: 7,
          titulo: "AK47",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Palay",
          tieneVideoclip: true,
          urlVideoclip: "",
          duracion: "",
          audio: "07. Predy - AK47 (con Palay)",
          videoAudio: "",
        },
        {
          order: 8,
          titulo: "Generación 80",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "08. Predy - Generacion 80",
          videoAudio: "",
        },
        {
          order: 9,
          titulo: "Contra el olimpo",
          producedBy: "Predy",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "09. Predy - Contra el olimpo",
          videoAudio: "",
        },
        {
          order: 10,
          titulo: "Tocamela otra vez",
          producedBy: "Predy",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "10. Predy - Tocamela otra vez",
          videoAudio: "",
        },
        {
          order: 11,
          titulo: "Dharmaggedon",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          featuring: "Chucky",
          urlVideoclip: "",
          duracion: "",
          audio: "11. Predy - Dharmaggedon (con Chucky)",
          videoAudio: "",
        },
      ],
    },
    {
      id: "258d5f42-6355-4ff4-9a8b-900244e91aa9",
      nombre: "2.0",
      portada: "https://mp3.hhgroups.com/albumes/Predy-Delantera_2.0-16042.jpg",
      contraportada:
        "https://mp3.hhgroups.com/albumes/Predy-Trasera_2.0-16042.jpg",
      fechaSalida: "2010-08-16",
      colaboradores: ["Eneko y Gareta", "Dj Erixon, Smilita, Koar, Bikos"],
      descargas: 6372,
      points: 322,
      descripcion:
        '2.0 Es el último trabajo de Predy donde notaremos un cambio en cuanto a estética y letras. Cuenta con temas más polémicos hablando de la piratería enfocándolo desde otro punto de vista, otros más temáticos bajo el género del diseño, y lo que es el single de esta maqueta "Electroman", además también incluye un remix de el tema de "El último titán". En la parte instrumental contamos con colaboraciones de Snak (RMD), Madrid Produze y Dj Wane. Los mcs colaboradores de este trabajo son: Eneko y Gareta, Smilita, Koar y Bikos. Todos los scratches corren a cuenta de Dj Erixon. Espero que disfrutéis de este trabajo. Más info:www.predy.es',

      canciones: [
        {
          order: 1,
          titulo: "Pirateria on",
          producedBy: "Snak",
          link: "https://example.com/estrellas-danzantes.mp3",
          featuring: "Dj Erixon",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "01. Predy - Pirateria on (con Dj Erixon)",
          videoAudio: "",
        },
        {
          order: 2,
          titulo: "Rabia contenida",
          producedBy: "Madrid produce",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Eneko y Gareta",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "02. Predy - Rabia contenida (con Eneko y Gareta)",
          videoAudio: "",
        },
        {
          order: 3,
          titulo: "Electroman",
          producedBy: "Predy",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: true,
          urlVideoclip: "",
          duracion: "",
          audio: "03. Predy - Electroman (con Dj Erixon)",
          videoAudio: "",
        },
        {
          order: 4,
          titulo: "Dyseno flow",
          producedBy: "Predy",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Smilita",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "04. Predy - Dyseno flow (con Smilita)",
          videoAudio: "",
        },
        {
          order: 5,
          titulo: "Y para colmo",
          producedBy: "Snak",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "05. Predy - Y para colmo (con Koar y Bikos)",
          videoAudio: "",
        },
        {
          order: 6,
          titulo: "2.0 evolution",
          producedBy: "Predy",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "06. Predy - 2.0 evolution",
          videoAudio: "",
        },
        {
          order: 7,
          titulo: "El ultimo titan (Remix)",
          producedBy: "Dj Wane",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "07. Predy - El ultimo titan (con Dj Erixon) (Remix)",
          videoAudio: "",
        },
      ],
    },

    {
      id: "80283cc3-a600-45ed-8c5a-82484862c152",
      nombre: "Mr Potato",
      portada: "/music/portadas/Mr potato - Cover.jpg",
      contraportada: "/music/portadas/Mr potato - Back cover.jpg",
      fechaSalida: "2011-11-11",
      colaboradores: [],
      descargas: 0,
      points: 0,
      descripcion: "",
      canciones: [
        {
          order: 1,
          titulo: "Presentación patillera",
          producedBy: "",
          link: "https://example.com/estrellas-danzantes.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "01. Predy - Presentacion patillera",
          videoAudio: "",
        },
        {
          order: 2,
          titulo: "Street Clap",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "02. Predy - Street clap",
          videoAudio: "",
        },
        {
          order: 3,
          titulo: "Rapcore",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Marko",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "03. Predy - Rapcore(Con Marko)",
          videoAudio: "",
        },
        {
          order: 4,
          titulo: "No nos moverán",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Palay",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "04. Predy - No nos moveran(Con Palay)",
          videoAudio: "",
        },
        {
          order: 5,
          titulo: "Aaaahh, Como?",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "05. Predy - Aaaahh, como",
          videoAudio: "",
        },
        {
          order: 6,
          titulo: "Humor negro",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Chucky",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "06. Predy - Humor Negro(Con Chucky)",
          videoAudio: "",
        },
        {
          order: 7,
          titulo: "21 Dias rapeando",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "07. Predy - 21 Dias rapeando",
          videoAudio: "",
        },
        {
          order: 8,
          titulo: "Predyagnostico (2004)",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "08. Predy - Predyagnostico (2004)",
          videoAudio: "",
        },
      ],
    },

    {
      id: "0848bc89-99bb-457a-a944-36ecd6af4f2e",
      nombre: "Dopamina",
      portada:
        "https://mp3.hhgroups.com/albumes/Predy-Delantera_Dopamina-29507.jpg",
      contraportada:
        "https://mp3.hhgroups.com/albumes/Predy-Trasera_Dopamina-29507.jpg",
      fechaSalida: "2012-07-12",
      colaboradores: ["Kapo", "Koar", "Smilita", "Kar"],
      descargas: 3013,
      points: 78,
      descripcion:
        "Dopamina es una maqueta que prueba hacer un tipo de rap diferente intentándolo enfocar un poco mas hacia un lado cómico y humorístico y intentando dar un rollo mas positivo al hiphop de hoy en día, cuanta con colaboraciones de Koar, Smilita, Kapo y Kar. Contacto:www.predy.es",
      canciones: [
        {
          order: 1,
          titulo: "La primera en la frente",
          producedBy: "",
          link: "https://example.com/estrellas-danzantes.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "01. Predy - La primera en la frente",
          videoAudio: "",
        },
        {
          order: 2,
          titulo: "No me dejan",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: true,
          urlVideoclip: "",
          duracion: "",
          audio: "02. Predy - No me dejan",
          videoAudio: "",
        },
        {
          order: 3,
          titulo: "Popeye el infiel",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Kapo 013",
          tieneVideoclip: true,
          urlVideoclip: "",
          duracion: "",
          audio: "03. Predy - Popeye el infiel (con Kapo)",
          videoAudio: "",
        },
        {
          order: 4,
          titulo: "Voy a romper internet",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Smilita",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "04. Predy - Voy a romper internet (con Smilita)",
          videoAudio: "",
        },
        {
          order: 5,
          titulo: "Danger",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Koar",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "05. Predy - Danger (con Koar)",
          videoAudio: "",
        },
        {
          order: 6,
          titulo: "Hiphoputa",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "06. Predy - Hiphoputa",
          videoAudio: "",
        },
        {
          order: 7,
          titulo: "Duchafobia",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "07. Predy - Duchafobia",
          videoAudio: "",
        },
        {
          order: 8,
          titulo: "Almas de barrio",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Kar",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "08. Predy - Almas de barrio (con Kar)",
          videoAudio: "",
        },
        {
          order: 9,
          titulo: "Lo sé, canto mal",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "09. Predy - Lo se canto mal",
          videoAudio: "",
        },
        {
          order: 10,
          titulo: "Rap game",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "10. Predy - Rap game",
          videoAudio: "",
        },
        {
          order: 11,
          titulo: "Fapman",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "11. Predy - Fapman",
          videoAudio: "",
        },
        {
          order: 12,
          titulo: "Dos caminos",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Smilita",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "12. Predy - Dos caminos (con Smilita)",
          videoAudio: "",
        },
        {
          order: 13,
          titulo: "Marketing de managers",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "13. Predy - Marketing de managers",
          videoAudio: "",
        },
        {
          order: 14,
          titulo: "Cntr + rap + supr",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "14. Predy - Cntrrapsupr",
          videoAudio: "",
        },
        {
          order: 15,
          titulo: "Salgo poco de fiesta",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "15. Predy - Salgo poco de fiesta",
          videoAudio: "",
        },
      ],
    },
    {
      id: "421a0fe4-f3ac-4b62-aca3-dc0d5f18e9f0",
      nombre: "Inestable",
      portada:
        "https://mp3.hhgroups.com/albumes/Predy-Inestable-39982_front.jpg",
      contraportada:
        "https://mp3.hhgroups.com/albumes/Predy-Inestable-39982_back.jpg",
      fechaSalida: "2014-07-12",
      colaboradores: ["Blon", "Dakob, Dj Dolmen, Kapo 013, Dawizard"],
      descargas: 1699,
      points: 22,
      descripcion:
        "Vuelve Predy con otro trabajo experimental, mas nostálgico, mas cachondo, mas loco, en definitiva mas... Predy, un disco que pretende separarse de la corriente rapistica que se esta haciendo en la actualidad, probando diferentes géneros, como el tecno, dubstep, y enfocándolo como ya viene siendo habitual desde el punto de vista del humor.",

      canciones: [
        {
          order: 1,
          titulo: "Hello world",
          producedBy: "",
          link: "https://example.com/estrellas-danzantes.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "01. Predy - Hello world",
          videoAudio: "",
        },
        {
          order: 2,
          titulo: "Inestable",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "02. Predy - Inestable",
          videoAudio: "",
        },
        {
          order: 3,
          titulo: "Se cagan encima",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: true,
          urlVideoclip: "",
          duracion: "",
          audio: "03. Predy - Se cagan encima",
          videoAudio: "",
        },
        {
          order: 4,
          titulo: "Acuérdate de mi cuando seas famoso",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Blon",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "04. Predy - Acuérdate de mi cuando seas famoso (con Blon)",
          videoAudio: "",
        },
        {
          order: 5,
          titulo: "En mis tiempos",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Dakob",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "05. Predy - En mis tiempos (con Dakob)",
          videoAudio: "",
        },
        {
          order: 6,
          titulo: "Ponte eufórico mix",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "06. Predy - Ponte eufórico mix",
          videoAudio: "",
        },
        {
          order: 7,
          titulo: "La mierda sabe a chocolate",
          producedBy: "Dj Dolmen",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "07. Predy - La mierda sabe a chocolate (con Dj Dolmen)",
          videoAudio: "",
        },
        {
          order: 8,
          titulo: "Mitades",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Kapo",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "08. Predy - Mitades (con Kapo 013)",
          videoAudio: "",
        },
        {
          order: 9,
          titulo: "What? what?",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "09. Predy - What what",
          videoAudio: "",
        },
        {
          order: 10,
          titulo: "Espantatias",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "10. Predy - Espantatias",
          videoAudio: "",
        },
        {
          order: 11,
          titulo: "Tengo un amigo que...",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          featuring: "Dawizard",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "11. Predy - Tengo un amigo que... (con Dawizard)",
          videoAudio: "",
        },
        {
          order: 12,
          titulo: "Toma!",
          producedBy: "",
          link: "https://example.com/viaje-sin-fin.mp3",
          tieneVideoclip: false,
          urlVideoclip: "",
          duracion: "",
          audio: "12. Predy - Toma!",
          videoAudio: "",
        },
      ],
    },
  ]

  return discos
}

const discos = getDiscos()
