import { Video } from "@/types/Video"

//Sacar el thumbnail de los videos con https://www.youtubethumbnaildownloader.com/

export function getVideoclips(): Video[] {
  const videoclips: Video[] = [
    {
      id: "f7e127d3-892d-40b9-9269-bb95f9b01598",
      titulo: "De tripas, corazón",
      thumbnail: "",
      fechaSalida: "2021-06-16",
      visualizacionesYoutube: 179,
      descripcion:
        "Tras un periodo inactivo, al final me he decidido y he hecho De tripas, corazón.",
      descripcionSugerida:
        "Emergiendo de una pausa, 'De tripas, corazón' es mi retorno al juego; una cruda manifestación de persistencia envuelta en ritmos.",
      featuring: "",
      beat: "Ramsay Beats",
      mezcla: "Cansino(PlaymoBeats)",
      originalLikes: 14,
      material: "",
      idYoutube: "W2Eujh_qvwU",
    },
    {
      id: "298103cc-e230-44dc-992c-090a6e9bec5e",
      titulo: "Cuarentrena",
      thumbnail: "",
      fechaSalida: "2020-03-28",
      visualizacionesYoutube: 994,
      descripcion:
        "Desde el confinamiento más extremo llega Cuarentrena un videoclip HomeMade que habla de la situación por la que está pasando el mundo actualmente, como siempre con el toque Predy. Espero que os guste, y no salgáis de casa, ¡¡no me seáis alantaos!!",
      descripcionSugerida:
        "'Cuarentrena' capta el eco de nuestro confinamiento, un reflejo homemade de estos tiempos revueltos, visto a través de mis ojos. Quédate en casa, vibra conmigo.",
      featuring: "",
      beat: "Ramsay Beats",
      mezcla: "Koar en Local12",
      originalLikes: 79,
      material: "",
      idYoutube: "__x5b4vmhiA",
    },
    {
      id: "c25581bf-8e79-478e-847a-8364e672dee1",
      titulo: "¿Qué será mañana?",
      thumbnail: "",
      fechaSalida: "2019-10-03",
      visualizacionesYoutube: 616,
      descripcion:
        "¿Que será mañana? ¿Será Futurama? ¿Habrá un mañana? ¡Vete tú a saber! De momento, lo único que sé es que tienes este tema para disfrutarlo eternamente.",
      descripcionSugerida:
        "Explorando incógnitas, '¿Qué será mañana?' es un viaje lírico hacia el futuro incierto, un himno a la incertidumbre con un beat eterno.",
      featuring: "",
      beat: "",
      mezcla: "Koar en Local12",
      originalLikes: 44,
      material: "",
      idYoutube: "JEFbi5zkq7",
    },

    {
      id: "d43b398c-e678-46b8-8b08-0d0f9b1ea90b",
      titulo: "Lo que ellos digan",
      thumbnail: "",
      fechaSalida: "2018-11-13",
      visualizacionesYoutube: 401,
      descripcion:
        "No hagáis caso a lo que digan, sed siempre vosotros mismos... Bueno, a menos que seáis mala persona, ahí si que os toca dejaros aconsejar :P",
      descripcionSugerida:
        "'Lo que ellos digan' es un himno a la autenticidad, un recordatorio de que ser uno mismo es la clave, salvo que necesites cambiar.",
      featuring: "Maria Serra",
      beat: "Ramsay Beats",
      mezcla: "Cansino (PlaymoBeats)",
      originalLikes: 20,
      material: "",
      idYoutube: "I2WQf2w-3vQ",
    },
    {
      id: "e83c56ba-4f55-4af8-a9d3-c4fbd4a5708d",
      titulo: "Mareado",
      thumbnail: "",
      fechaSalida: "2018-07-31",
      visualizacionesYoutube: 425,
      descripcion: "Ya veis como vivo la vida... Mareado.",
      descripcionSugerida:
        "En 'Mareado', te llevo por el torbellino de mi día a día; una vida vivida al límite, entre el desenfreno y la pasión por lo que hago.",
      featuring: "",
      beat: "RP beats",
      mezcla: "Cansino (PlaymoBeats)",
      originalLikes: 27,
      material: "",
      idYoutube: "Eh2qaFJphNk",
    },
    {
      id: "fa8b2b4e-6d04-4697-8c6d-2e1b4138a4a0",
      titulo: "Oro",
      thumbnail: "",
      fechaSalida: "2017-12-20",
      visualizacionesYoutube: 1102,
      descripcion:
        "Valemos ORO. Pero para que te quieran los demás, quiérete tú primero.",
      descripcionSugerida:
        "'Oro' es un reflejo de nuestro valor intrínseco, una oda a la autoestima que resuena con el brillo dorado del amor propio.",
      featuring: "",
      beat: "Ramsay Beats",
      mezcla: "Cansino (PlaymoBeats)",
      originalLikes: 79,
      material: "",
      idYoutube: "BPVTpwDeyZs",
    },
    {
      id: "ac4f2ee8-7e41-46f4-8c2e-3b1c4a4e4c19",
      titulo: "Conecta2",
      thumbnail: "",
      fechaSalida: "2017-06-14",
      visualizacionesYoutube: 321,
      descripcion:
        "¿Estamos conectados? Este tema va por todos los que me apoyan y por los que me apoyarán en un futuro, gracias a todos.",
      descripcionSugerida:
        "'Conecta2' es un agradecimiento, un lazo que se extiende a través de la música, conectándonos más allá de las distancias. Gracias por estar ahí.",
      featuring: "",
      beat: "",
      mezcla: "Koar Beats (SoulTeam)",
      originalLikes: 30,
      material: "",
      idYoutube: "4ziZ0_3XxLk",
    },

    {
      id: "c4f5g6h7-i8j9-k10l-m11n-12o13p14q15r",
      titulo: "Skate for Life",
      thumbnail: "",
      fechaSalida: "2017-02-09",
      visualizacionesYoutube: 1351,
      descripcion:
        "En mi disco 'El último titán' (2009) dediqué un tema entero a una de mis pasiones, el Skateboard, con la canción 'Predyflip 360'. Los tiempos evolucionan y mi rap también, así que he querido volver a dedicarle otra canción a este deporte, gracias a Dj Xino el tema cuenta con Scratches de Frases del tema inicial ('Predyflip 360')",
      descripcionSugerida:
        "'Skate for Life' es un tributo a mi pasión eterna: el skate. Este tema, evolucionado desde 'Predyflip 360', lleva mi amor por el skate a nuevos horizontes. Gracias a Dj Xino por sumar su magia.",
      featuring: "Dj Xino",
      beat: "",
      mezcla: "Cansino en NPF",
      originalLikes: 27,
      material: "",
      idYoutube: "FPd1NV3diPg",
    },
    {
      id: "d5e6f7g8-h9i10-j11k-l12m-13n14o15p16q",
      titulo: "Esencia de Gorila",
      thumbnail: "",
      fechaSalida: "2016-07-19",
      visualizacionesYoutube: 364,
      descripcion: "",
      descripcionSugerida:
        "En 'Esencia de Gorila', dejo que la música hable por sí misma. Sin palabras, este track es pura vibra y energía bruta, un grito primal en forma de rap.",
      featuring: "",
      beat: "",
      mezcla: "",
      originalLikes: 23,
      material: "",
      idYoutube: "SRKYmLdqtGE",
    },
    {
      id: "e7f8g9h0-i1j2-k3l4-m5n6-7o8p9q0r1s2t",
      titulo: "Escucha Piensa Actua",
      thumbnail: "",
      fechaSalida: "2016-06-25",
      visualizacionesYoutube: 393,
      descripcion:
        "Canción realizada con el motivo de las elecciones de España 26J, en la cual se promueve el derecho a votar.",
      descripcionSugerida:
        "'Escucha Piensa Actua' es un llamado a la acción, inspirado en las elecciones. Este tema invita a reflexionar sobre nuestro poder y responsabilidad cívica, marcando el ritmo del cambio.",
      featuring: "",
      beat: "",
      mezcla: "Cansino (PlaymoBeats)",
      originalLikes: 28,
      material: "",
      idYoutube: "37nzD5mUQ7U",
    },

    {
      id: "g8h9i0j1-k2l3-m4n5-o6p7-q8r9s0t1u2v",
      titulo: "Cervantes en Rap",
      thumbnail: "",
      fechaSalida: "2016-05-27",
      visualizacionesYoutube: 1009,
      descripcion:
        "Esta es mi inscripción para el concurso de Cervantes en Rap del festival de almagro",
      descripcionSugerida:
        "'Cervantes en Rap' te lleva a un viaje lírico a través de la historia, fusionando el legado de Cervantes con el ritmo inconfundible del rap. Es mi homenaje a un gigante de la literatura, adaptado a la era moderna.",
      featuring: "",
      beat: "",
      mezcla: "",
      originalLikes: 41,
      material: "",
      idYoutube: "DTcVJC16x90",
    },
    {
      id: "h0i1j2k3-l4m5-n6o7-p8q9-r0s1t2u3v4w",
      titulo: "TBP audition d(-_-)b",
      thumbnail: "",
      fechaSalida: "2016-03-12",
      visualizacionesYoutube: 227,
      descripcion: "",
      descripcionSugerida:
        "'TBP audition d(-_-)b' marca mi audición para TBP, encapsulando mi esfuerzo y pasión. Sin palabras necesarias, cada beat cuenta la historia de mi determinación.",
      featuring: "",
      beat: "",
      mezcla: "",
      originalLikes: 17,
      material: "",
      idYoutube: "_oJ33H2BVQc",
    },
    {
      id: "i1j2k3l4-m5n6-o7p8-q9r0-s1t2u3v4w5x",
      titulo: "No solo digo tonterías",
      thumbnail: "",
      fechaSalida: "2015-11-15",
      visualizacionesYoutube: 410,
      descripcion:
        "Tema inedito... porque yo también puedo hacer temas tranquilos y reflexivos",
      descripcionSugerida:
        "'No solo digo tonterías' revela una faceta más serena y reflexiva de mi música. Es una introspección lírica, un lado diferente que habla con suavidad pero resonancia.",
      featuring: "",
      beat: "",
      mezcla: "",
      originalLikes: 19,
      material: "",
      idYoutube: "t5picGJLnEE",
    },
    {
      id: "j2k3l4m5-n6o7-p8q9-r0s1-t2u3v4w5x6y",
      titulo: "Speech Therapist",
      thumbnail: "",
      fechaSalida: "2015-06-28",
      visualizacionesYoutube: 338,
      descripcion:
        "Tema inedito... porque yo también puedo hacer temas tranquilos y reflexivos",
      descripcionSugerida:
        "Con 'Speech Therapist', te invito a una sesión de terapia a través de la música. Un espacio donde las palabras curan, reconfortan y transforman.",
      featuring: "Correpa",
      beat: "A Lil Different EP",
      mezcla: "",
      originalLikes: 8,
      material: "",
      idYoutube: "KAIW6HVZIcg",
    },

    {
      id: "k3l4m5n6-o7p8-q9r0-s1t2-u3v4w5x6y7z",
      titulo: "Funktastico! (Especial 307 suscriptores)",
      thumbnail: "",
      fechaSalida: "2015-05-01",
      visualizacionesYoutube: 497,
      descripcion:
        "Para agradecer que últimamente esta aumentando mi número de suscriptores e preparado un vídeo cantando un fragmento de un tema inédito, espero que os guste, un saludo!",
      descripcionSugerida:
        "'Funktastico!' es un gesto de gratitud hacia vosotros, mis seguidores. A través de un fragmento inédito, celebro cada suscripción como un paso más en este viaje juntos. ¡Gracias por ser parte!",
      featuring: "",
      beat: "",
      mezcla: "",
      originalLikes: 21,
      material: "",
      idYoutube: "vp3-Umq7LbE",
    },
    {
      id: "l4m5n6o7-p8q9-r0s1-t2u3-v4w5x6y7z8a",
      titulo: "ODR2015 Aspirante Predy",
      thumbnail: "",
      fechaSalida: "2015-03-17",
      visualizacionesYoutube: 1523,
      descripcion: "Participación para el evento de www.olimpiadadelrap.com",
      descripcionSugerida:
        "En 'ODR2015 Aspirante Predy', me sumerjo en la competencia de www.olimpiadadelrap.com con todo lo que tengo. Este videoclip es más que una participación; es mi declaración de presencia en la escena.",
      featuring: "",
      beat: "",
      mezcla: "",
      originalLikes: 51,
      material: "",
      idYoutube: "ePUQtNHLvF4",
    },
    {
      id: "m5n6o7p8-q9r0-s1t2-u3v4-w5x6y7z8a9b",
      titulo: "One shot",
      thumbnail: "",
      fechaSalida: "2014-09-23",
      visualizacionesYoutube: 3028,
      descripcion: "One shot, vídeo a una sola toma.",
      descripcionSugerida:
        "'One shot' es un desafío artístico, capturado en una sola toma, donde cada momento es irrepetible. Es la esencia del rap en su forma más pura y espontánea.",
      featuring: "",
      beat: "",
      mezcla: "",
      originalLikes: 67,
      material: "",
      idYoutube: "jRRirY5SARs",
    },
    {
      id: "m5n6o7p8-q9r0-s1t2-u3v4-w5x6y7z8a9b",
      titulo: "En mis tiempos",
      thumbnail: "",
      fechaSalida: "2014-09-10",
      visualizacionesYoutube: 9441,
      descripcion:
        "Videoclip nostálgico de motion graphics, pertenece al trabajo de Inestable",
      descripcionSugerida: "Hay que crearla",
      featuring: "Dakob",
      beat: "",
      mezcla: "",
      originalLikes: 83,
      material: "",
      idYoutube: "rD_CA552kFM",
    },
    {
      id: "n6o7p8q9-r0s1-t2u3-v4w5-x6y7z8a9b0c",
      titulo: "3 Días",
      thumbnail: "",
      fechaSalida: "2014-08-07",
      visualizacionesYoutube: 1279,
      descripcion:
        "Videoclip 3 Días, la idea del tema es que a sido preparado todo en tan solo 3 días, se a escrito, grabado, mezclado, grabado el vídeo y editado en tan solo 3 días sin la colaboración de ninguna persona.",
      descripcionSugerida:
        "'3 Días' es el resultado de un reto personal intenso: crear un tema completo en solo tres días. Desde la letra hasta el videoclip, cada aspecto fue un sprint de creatividad y dedicación.",
      featuring: "",
      beat: "",
      mezcla: "",
      originalLikes: 29,
      material: "",
      idYoutube: "y6aKCda0Dps",
    },
    {
      id: "o7p8q9r0-s1t2-u3v4-w5x6-y7z8a9b0c1d",
      titulo: "Se cagan encima",
      thumbnail: "",
      fechaSalida: "2014-07-31",
      visualizacionesYoutube: 3599,
      descripcion:
        "Videoclip en el cual me va creciendo la barba a la vez que canto el track y unas 80 personas participan en el estribillo.",
      descripcionSugerida:
        "'Se cagan encima' no es solo un videoclip, es una experiencia colectiva. Con una barba que crece y una multitud que se une, este tema captura un momento único y compartido.",
      featuring: "",
      beat: "Knife Party",
      mezcla: "",
      originalLikes: 57,
      material: "",
      idYoutube: "bRcMtRaQgxw",
    },

    {
      id: "p8q9r0s1-t2u3-v4w5-x6y7-z8a9b0c1d2e",
      titulo: "Track-Tor Yellow",
      thumbnail: "",
      fechaSalida: "2014-04-18",
      visualizacionesYoutube: 236,
      descripcion:
        "Un Track de esos que me escribo, grabo y hago un video en un día.",
      descripcionSugerida:
        "'Track-Tor Yellow' es un testimonio de creatividad y eficiencia: una idea que cobró vida en menos de 24 horas. Es la esencia del arte espontáneo, capturado en ritmo y rima.",
      featuring: "",
      beat: "",
      mezcla: "",
      originalLikes: 10,
      material: "",
      idYoutube: "SFEP7rv64N0",
    },
    {
      id: "q9r0s1t2-u3v4-w5x6-y7z8-a9b0c1d2e3f",
      titulo: "ODR2014 Aspirante Predy",
      thumbnail: "",
      fechaSalida: "2014-02-20",
      visualizacionesYoutube: 2776,
      descripcion:
        "Vídeo de presentación de Predy para http://www.olimpiadadelrap.com/",
      descripcionSugerida:
        "Mi entrada a 'ODR2014 Aspirante Predy' marca mi ambición y pasión por destacar en el mundo del rap. Es una declaración audaz de mi arte y mi espíritu competitivo.",
      featuring: "",
      beat: "",
      mezcla: "",
      originalLikes: 91,
      material: "",
      idYoutube: "Z2LGbPVeA1A",
    },
    {
      id: "r0s1t2u3-v4w5-x6y7-z8a9-b0c1d2e3f4g",
      titulo: "Electroman",
      thumbnail: "",
      fechaSalida: "2014-01-24",
      visualizacionesYoutube: 1277,
      descripcion:
        "Este videoclip del track de Electroman del disco de 2.0, tenía que salir en 2010 pero por diversos motivos no vio la luz, y ahora 4 años mas tarde vuelvo a recuperar las tomas para poder recuperar el proyecto y poderoslo enseñar de forma Inedita.",
      descripcionSugerida:
        "'Electroman' emerge de las sombras del pasado, un proyecto renacido que conecta el ayer con el hoy. Es más que un videoclip; es un puente entre décadas, finalmente revelado.",
      featuring: "",
      beat: "",
      mezcla: "",
      originalLikes: 18,
      material: "",
      idYoutube: "nI0BUU-n5OY",
    },
    {
      id: "s1t2u3v4-w5x6-y7z8-a9b0-c1d2e3f4g5h",
      titulo: "#1Minuto",
      thumbnail: "",
      fechaSalida: "2013-09-20",
      visualizacionesYoutube: 2020,
      descripcion: "Videoclip de #1Minuto.",
      descripcionSugerida:
        "'#1Minuto' es una cápsula de tiempo, una inmersión profunda en el ritmo y la lírica condensada en sesenta segundos de fuego puro. Es intenso, rápido y memorable.",
      featuring: "",
      beat: "",
      mezcla: "Koar (Soulteam)",
      originalLikes: 33,
      material: "",
      idYoutube: "H4zOadwr6Ck",
    },
    {
      id: "t2u3v4w5-x6y7-z8a9-b0c1-d2e3f4g5h6i",
      titulo: "Aire 2013",
      thumbnail: "",
      fechaSalida: "2013-08-19",
      visualizacionesYoutube: 2020,
      descripcion:
        "Os dejo con un tema Inédito que no saldrá en ningún trabajo mio, simplemente es un tema suelto que escribí en 1 horilla por el mero motivo de que me apetecía.",
      descripcionSugerida:
        "'Aire 2013' fluye como una brisa fresca, una pieza nacida de un impulso creativo espontáneo. Es un destello de inspiración capturado en música, compartido directamente desde mi esencia a ti.",
      featuring: "",
      beat: "",
      mezcla: "",
      originalLikes: 14,
      material: "",
      idYoutube: "dwYKAwv98_A",
    },
    {
      id: "u3v4w5x6-y7z8-a9b0-c1d2-e3f4g5h6i7j",
      titulo: "Encontré a Wifly",
      thumbnail: "",
      fechaSalida: "2012-12-25",
      visualizacionesYoutube: 579,
      descripcion:
        "Tema para el concurso de: S-Kill da Beat de MuthaFunk Company / La canción esta inspirada en el tema de Donde esta wifly? del grupo sevillano SFDK.",
      descripcionSugerida:
        "'Encontré a Wifly' es mi oda al juego del escondite que jugamos todos. Inspirado por SFDK, este track es un guiño al arte de buscar y finalmente encontrar.",
      featuring: "",
      beat: "",
      mezcla: "Koar (Soulteam)",
      originalLikes: 15,
      material: "",
      idYoutube: "6_zPkenAS94",
    },
    {
      id: "v4w5x6y7-z8a9-b0c1-d2e3-f4g5h6i7j8k",
      titulo: "No me dejan",
      thumbnail: "",
      fechaSalida: "2012-11-01",
      visualizacionesYoutube: 15042,
      descripcion:
        "Tema para el concurso de: S-Kill da Beat de MuthaFunk Company / La canción esta inspirada en el tema de Donde esta wifly? del grupo sevillano SFDK.",
      descripcionSugerida:
        "'No me dejan' es un grito contra las barreras, una declaración de rebeldía musical que rinde tributo a las raíces de SFDK, mezclando respeto y evolución.",
      featuring: "Btta Designs",
      beat: "",
      mezcla: "",
      originalLikes: 110,
      material: "",
      idYoutube: "GgvcE-SOj10",
    },
    {
      id: "w5x6y7z8-a9b0-c1d2-e3f4-g5h6i7j8k9l",
      titulo: "2 a Sako",
      thumbnail: "",
      fechaSalida: "2012-05-13",
      visualizacionesYoutube: 447,
      descripcion: "Tema inedito 2012",
      descripcionSugerida:
        "'2 a Sako' es puro fuego, una entrega sin reservas de ritmo y rimas crudas. Captura el espíritu del 2012 con un flujo imparable y una energía que desafía el tiempo.",
      featuring: "",
      beat: "",
      mezcla: "",
      originalLikes: 11,
      material: "",
      idYoutube: "aAk4XwIf4s0",
    },
    {
      id: "x6y7z8a9-b0c1-d2e3-f4g5-h6i7j8k9l0m",
      titulo: "Voy a romper internet",
      thumbnail: "",
      fechaSalida: "2012-02-01",
      visualizacionesYoutube: 11208,
      descripcion: "Tema inedito 2012",
      descripcionSugerida:
        "'Voy a romper internet' es más que una canción; es una profecía auto-cumplida. Con Smilita y el beat de Er Guille, nos lanzamos a la conquista digital, listos para hacer historia.",
      featuring: "Smilita",
      beat: "Er Guille",
      mezcla: "Koar (Solteam)",
      originalLikes: 234,
      material: "",
      idYoutube: "foRKD4V0LzM",
    },
    {
      id: "y7z8a9b0-c1d2-e3f4-g5h6-i7j8k9l0m1n",
      titulo: "Presentación Dopamina",
      thumbnail: "",
      fechaSalida: "2011-08-13",
      visualizacionesYoutube: 705,
      descripcion:
        "Un pequeño adelanto de lo que podréis ver en mi nuevo trabajo musical llamado Dopamina, espero que lo disfrutéis, en breves pondré por aquí el enlace para poderlo descargar de forma gratuita, un saludo a todos.",
      descripcionSugerida:
        "'Presentación Dopamina' es la ventana a mi nueva era musical, un aperitivo de lo que está por venir. Este adelanto es solo el inicio de un viaje sonoro que promete elevar tus sentidos.",
      featuring: "",
      beat: "",
      mezcla: "",
      originalLikes: 11,
      material: "",
      idYoutube: "TVaNb6o4es4",
    },

    {
      id: "z8a9b0c1-d2e3-f4g5-h6i7-j8k9l0m1n2o",
      titulo: "Ak 47",
      thumbnail: "",
      fechaSalida: "2009-12-31",
      visualizacionesYoutube: 2929,
      descripcion:
        "Aquí os traigo el nuevo videoclip junto a Palay del tema AK-47 de la maqueta El Último Titán, espero que lo disfruteis, por ultimo un agradecimiento a todos los que participaron en el videoclip.",
      descripcionSugerida:
        "'Ak 47', un disparo de pura energía con Palay, es la esencia de 'El Último Titán'. Este videoclip es un agradecimiento vibrante a quienes dieron vida a cada frame. Disfrútenlo, es fuego puro.",
      featuring: "",
      beat: "",
      mezcla: "",
      originalLikes: 29,
      material: "",
      idYoutube: "jl0TYIzhY70",
    },
    {
      id: "a9b0c1d2-e3f4-g5h6-i7j8-k9l0m1n2o3p",
      titulo: "Trailer videoclip Ak 47",
      thumbnail: "",
      fechaSalida: "2009-10-22",
      visualizacionesYoutube: 613,
      descripcion:
        "El dia 1 de enero despues de las campanadas sera colgado el videoclip de Ak 47, de la maqueta de El ultimo titan, disponible en WWW.PREDY.ES",
      descripcionSugerida:
        "El 'Trailer videoclip Ak 47' es la chispa antes del estallido, un adelanto que prepara el escenario para la revelación de 'Ak 47'. Marquen sus calendarios; el titan está por llegar.",
      featuring: "",
      beat: "",
      mezcla: "",
      originalLikes: 1,
      material: "",
      idYoutube: "daPMGT6XXzU",
    },
    {
      id: "b0c1d2e3-f4g5-h6i7-j8k9-l0m1n2o3p4q",
      titulo: "Videoclip Generación 80",
      thumbnail: "",
      fechaSalida: "2009-07-28",
      visualizacionesYoutube: 10364,
      descripcion:
        "Videoclip oficial del tema Generación 80 de la maqueta gratuita El Último Titán.",
      descripcionSugerida:
        "'Videoclip Generación 80' nos sumerge en un viaje nostálgico, un homenaje a la época dorada. Es un encuentro entre generaciones, unidos por 'El Último Titán'.",
      featuring: "",
      beat: "",
      mezcla: "",
      originalLikes: 77,
      material: "",
      idYoutube: "VaZtNJOoZ1Y",
    },
    {
      id: "c1d2e3f4-g5h6-i7j8-k9l0-m1n2o3p4q5r",
      titulo: "Concierto El último titán, Rambla prim.",
      thumbnail: "",
      fechaSalida: "2009-06-14",
      visualizacionesYoutube: 614,
      descripcion:
        "Concierto de Predy, de el tema El ultimo titan, en Rambla prim, junto a palay.",
      descripcionSugerida:
        "El 'Concierto El último titán, Rambla prim' captura la esencia viva de 'El Último Titán' en acción. Junto a Palay, este concierto es una pieza clave de nuestro viaje musical.",
      featuring: "",
      beat: "",
      mezcla: "",
      originalLikes: 3,
      material: "",
      idYoutube: "oNNgdmP7K8M",
    },
  ]

  return videoclips
}
